# Generated by Django 6.0 on 2026-01-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_client_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Disponible'), ('IN_USE', 'En Service'), ('MAINTENANCE', 'En Maintenance')], default='AVAILABLE', max_length=20),
        ),
    ]
