# Generated by Django 6.0 on 2026-01-03 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_shipment_updated_at_alter_shipment_driver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_DUTY', 'On Duty'), ('OFF_DUTY', 'Off Duty')], default='AVAILABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='logistics.driver'),
        ),
    ]
