# Generated by Django 6.0 on 2026-01-03 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_driver_status_alter_shipment_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='logistics.driver'),
        ),
    ]
