# Generated by Django 6.0 on 2026-01-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_alter_shipment_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='hire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
