# Generated by Django 6.0 on 2026-01-03 19:32

import django.db.models.deletion
import logistics.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0008_driver_address_driver_email_driver_hire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_info',
            field=models.CharField(help_text='Format: 0555123456', max_length=255, validators=[logistics.models.validate_algerian_phone]),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.CharField(help_text='Format: 01123456 (8 chiffres)', max_length=50, unique=True, validators=[logistics.models.validate_algerian_license]),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(help_text='Format: 0555123456', max_length=20, validators=[logistics.models.validate_algerian_phone]),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('AGENT', 'Transport Agent'), ('DRIVER', 'Driver')], default='AGENT', max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(help_text='Format: 123456-16', max_length=20, unique=True, validators=[logistics.models.validate_algerian_plate]),
        ),
    ]
