# Generated by Django 6.0 on 2026-01-07 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0010_user_reset_token_user_reset_token_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='duration_hours',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='fuel_consumption',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='incidents',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PLANNED', max_length=20),
        ),
        migrations.AlterField(
            model_name='tour',
            name='shipments',
            field=models.ManyToManyField(blank=True, related_name='tours', to='logistics.shipment'),
        ),
    ]
