# Generated by Django 6.0 on 2026-01-07 18:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0012_claim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='driver',
        ),
        migrations.AlterField(
            model_name='claim',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='logistics.client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='claim',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='logistics.shipment'),
        ),
    ]
