# Generated by Django 6.0 on 2026-01-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0013_remove_claim_driver_alter_claim_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='customs_cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shipment',
            name='customs_currency',
            field=models.CharField(blank=True, default='DZD', help_text='Currency code (e.g., DZD, USD, EUR)', max_length=3),
        ),
        migrations.AddField(
            model_name='shipment',
            name='customs_declaration',
            field=models.TextField(blank=True, help_text='Customs declaration details', null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='customs_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Declared value for customs', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='destination_country',
            field=models.CharField(blank=True, help_text='Destination country', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='hs_code',
            field=models.CharField(blank=True, help_text='Harmonized System (HS) code for customs', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='is_international',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shipment',
            name='origin_country',
            field=models.CharField(blank=True, help_text="Country of origin (e.g., 'Algeria', 'France')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='requires_customs_clearance',
            field=models.BooleanField(default=False),
        ),
    ]
